#!/usr/bin/env python

import sys
from Bio import AlignIO
from Bio.Align import AlignInfo

try:
	input_file = sys.argv[1]
	output_file = sys.argv[2]
	alignment = AlignIO.read(input_file, "fasta")
	summary_align = AlignInfo.SummaryInfo(alignment)
	consensus = summary_align.dumb_consensus(threshold=0.1,ambiguous='N')
	print(len(consensus))

	with open(output_file, 'a') as the_file:
		the_file.write('>consensus\n')
		the_file.write(str(consensus))
		the_file.write('\n')
except:
	print("Usage: get_consensus input.fa output.fa")

